### ISSUE TITLE
AttributeError: module 'keras' has no attribute 'config' when importing with Keras 3

### ISSUE THREAD

**Issue by jedlimlx** [keras-team/keras-nlp#1279] opened 2023-10-20 09:20 UTC
**Describe the bug**
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-9123bfa8a6de> in <cell line: 1>()
----> 1 import keras_nlp

6 frames
/usr/local/lib/python3.10/dist-packages/keras_nlp/backend/config.py in backend()
     90 
     91         return keras_core.config.backend()
---> 92     return keras.config.backend()

AttributeError: module 'keras' has no attribute 'config'
```

When the latest version of keras 3 and keras NLP is installed, importing keras NLP does not work.

**To Reproduce**
https://colab.research.google.com/gist/jedlimlx/ad3aa49f5a981997055a41b2b5b4d23a/keras-nlp-bug.ipynb

Install the latest version of keras 3 and keras NLP, then import keras_nlp.

**Expected behavior**
I would expect it to import with no errors, according to https://github.com/keras-team/keras-nlp/commit/f6d240bcff1fee7ec41b71ebfccb8c9691c6c796.

**Additional context**
Nil

**Would you like to help us fix it?**
No

**Comment by mattdangerw** [comment] 2023-10-20 18:30
Thanks for the bug!

This is actually because `!pip install git+https://github.com/keras-team/keras` is not a supported way to install keras. There is a build script to explicitly export API symbols--you need to run `python pip_build.py --install`. https://github.com/keras-team/keras#local-installation Without that, you get an `import keras` that seems find but is missing a lot of the Keras API.

**Comment by mattdangerw** [comment] 2023-10-20 18:45
This is a timely bug though. It has been somewhat tricky to build Keras and KerasNLP from source because TensorFlow is pinning particular versions of Keras and things conflict easily. We are going to recommend a flow based on nightly tensoflow for the time being, with this hitting the stable Keras and TensorFlow release in the coming months.

Here's how to build KerasNLP and Keras from source in colab:
https://colab.sandbox.google.com/gist/mattdangerw/2c797a134d97a7a13bda39352fe3d30b/keras-kerasnlp-from-source.ipynb

And I will be updating our `requirements.txt` files to switch over to nightlies for now, so you can just `pip install -r requirements.txt` to get a working keras-nlp environment that will run against the keras 3 nightly package.

**Comment by mattdangerw** [comment] 2023-10-20 18:46
Going to close this as I think everything is working as intended, but feel free to re-open if more questions.

**Closed by mattdangerw** 2023-10-20 18:46 UTC
Labels: bug
